package unindra.modules.datastore.budget.ui;

import java.util.Date;
import java.math.BigDecimal;
import java.time.ZoneId;
import java.util.Calendar;
import javax.swing.JOptionPane;

import unindra.modules.datastore.budget.service.BudgetService;
import unindra.modules.datastore.budget.model.Budget;
import unindra.modules.datastore.coa.ui.CoaList;

public class BudgetForm extends javax.swing.JFrame {

    private BudgetList list;

    private Budget selectedData;
    
    private Integer coaId;

    public BudgetForm(BudgetList list, Budget data) {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        this.list = list;
        if (data != null) {
            title.setText("Edit Data Anggaran");
            selectedData = data;
            coaId = data.getCoaId();
            fCoaName.setText(data.getCoaName());
            fPeriodStart.setDate(Date.from(data.getPeriodStart().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            fPeriodEnd.setDate(Date.from(data.getPeriodEnd().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            fAmount.setText(data.getAmount().toPlainString());
        } else {
            Calendar cal = Calendar.getInstance();
            cal.set(Calendar.DAY_OF_MONTH, 1);
            fPeriodStart.setDate(cal.getTime());
            cal.set(Calendar.DAY_OF_MONTH, cal.getActualMaximum(Calendar.DAY_OF_MONTH));
            fPeriodEnd.setDate(cal.getTime());
        }
    }

    private void lookupCoa() {
        CoaList.openLookup(coa -> {
            if (coa != null) {
                coaId = coa.getId();
                fCoaName.setText(coa.getName());
                fPeriodStart.requestFocus(true);
            }
        }, "child", 0);
    }
    
    private void save() {
        Budget data = new Budget();
        data.setCoaId(coaId);
        data.setPeriodStart(fPeriodStart.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        data.setPeriodEnd(fPeriodEnd.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        try {
            BigDecimal amount = new BigDecimal(fAmount.getText());
            data.setAmount(amount);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Nilai anggaran harus berupa angka.");
        }

        if (selectedData == null) {
            BudgetService.create(data);
        } else {
            data.setId(selectedData.getId());
            BudgetService.update(data);
        }
        list.loadData();
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new unindra.core.Background();
        lCoaName = new javax.swing.JLabel();
        lPeriodStart = new javax.swing.JLabel();
        lPeriodEnd = new javax.swing.JLabel();
        bSave = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        fCoaName = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        fPeriodStart = new com.toedter.calendar.JDateChooser();
        lAmount = new javax.swing.JLabel();
        fAmount = new javax.swing.JTextField();
        fPeriodEnd = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lCoaName.setBackground(new java.awt.Color(204, 255, 255));
        lCoaName.setText("Kategori Keuangan");

        lPeriodStart.setBackground(new java.awt.Color(204, 255, 255));
        lPeriodStart.setText("Awal Periode");

        lPeriodEnd.setBackground(new java.awt.Color(204, 255, 255));
        lPeriodEnd.setText("Akhir Periode");

        bSave.setText("Simpan");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bCancel.setText("Batal");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        fCoaName.setEditable(false);
        fCoaName.setText("Pilih kategori keuangan...");
        fCoaName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fCoaNameMouseClicked(evt);
            }
        });
        fCoaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCoaNameActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        title.setText("Tambah Data Anggaran");

        fPeriodStart.setDateFormatString("d-MMM-yyyy");

        lAmount.setBackground(new java.awt.Color(204, 255, 255));
        lAmount.setText("Nilai Anggaran");

        fAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fAmount.setText("0");

        fPeriodEnd.setDateFormatString("d-MMM-yyyy");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(bCancel)
                                .addGap(18, 18, 18)
                                .addComponent(bSave))
                            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(background1Layout.createSequentialGroup()
                                    .addComponent(lAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addComponent(lPeriodEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fPeriodEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addComponent(lPeriodStart, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fPeriodStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addComponent(lCoaName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fCoaName, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(301, 301, 301))))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(title)
                .addGap(57, 57, 57)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCoaName)
                    .addComponent(fCoaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPeriodStart)
                    .addComponent(fPeriodStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPeriodEnd)
                    .addComponent(fPeriodEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAmount))
                .addGap(136, 136, 136)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bCancel))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        save();
    }//GEN-LAST:event_bSaveActionPerformed

    private void fCoaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCoaNameActionPerformed
        lookupCoa();
    }//GEN-LAST:event_fCoaNameActionPerformed

    private void fCoaNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fCoaNameMouseClicked
        lookupCoa();
    }//GEN-LAST:event_fCoaNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BudgetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BudgetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BudgetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BudgetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BudgetForm(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bSave;
    private unindra.core.Background background1;
    private javax.swing.JTextField fAmount;
    private javax.swing.JTextField fCoaName;
    private com.toedter.calendar.JDateChooser fPeriodEnd;
    private com.toedter.calendar.JDateChooser fPeriodStart;
    private javax.swing.JLabel lAmount;
    private javax.swing.JLabel lCoaName;
    private javax.swing.JLabel lPeriodEnd;
    private javax.swing.JLabel lPeriodStart;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
