CREATE TABLE IF NOT EXISTS budgets (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	coa_id INTEGER NOT NULL, -- relasi ke chart_of_accounts.id
	period_start DATE NOT NULL,
	period_end DATE NOT NULL,
	amount NUMERIC NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
