CREATE TABLE IF NOT EXISTS journals (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		transaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
		coa_id INTEGER NOT NULL,
		debit DOUBLE PRECISION DEFAULT 0,
		credit DOUBLE PRECISION DEFAULT 0
);