package unindra.modules.datastore.coa.ui;

import unindra.modules.datastore.coa.model.Coa;
import unindra.modules.datastore.coa.service.CoaService;
import javax.swing.ButtonGroup;



public class ChartOfAccountForm extends javax.swing.JFrame {

    private Coa coaSelected;
    private ChartOfAccountList coaList;
    
   public ChartOfAccountForm(ChartOfAccountList coaList, Coa coaSelected){
        initComponents();
        pack();
        setLocationRelativeTo(null);
        ButtonGroup groupTunai = new ButtonGroup();
        groupTunai.add(rtunaiy);
        groupTunai.add(rtunait);

        this.coaList = coaList;
        
        if (coaSelected != null) {
            this.coaSelected = coaSelected;
            tid.setText(String.valueOf(coaSelected.getId()));
            tsubid.setText(String.valueOf(coaSelected.getParentId()));
            tnama.setText(coaSelected.getName());
            tkode.setText(String.valueOf(coaSelected.getCode()));
            jckategori.setSelectedItem(coaSelected.getCategoryId());
            rtunaiy.setSelected(coaSelected.getIsCash());
            rtunait.setSelected(!coaSelected.getIsCash());

        }
    
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        background1 = new unindra.core.Background();
        lCode = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lArea = new javax.swing.JLabel();
        lCapacity = new javax.swing.JLabel();
        bSave = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        tid = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        lUser1 = new javax.swing.JLabel();
        rtunaiy = new javax.swing.JRadioButton();
        rtunait = new javax.swing.JRadioButton();
        lNote2 = new javax.swing.JLabel();
        jckategori = new javax.swing.JComboBox<>();
        tsubid = new javax.swing.JTextField();
        lCapacity1 = new javax.swing.JLabel();
        tkode = new javax.swing.JTextField();
        bHapus = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lCode.setBackground(new java.awt.Color(204, 255, 255));
        lCode.setText("ID");
        background1.add(lCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lName.setBackground(new java.awt.Color(204, 255, 255));
        lName.setText("Sub ID");
        background1.add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        lArea.setBackground(new java.awt.Color(204, 255, 255));
        lArea.setText("Kategori");
        background1.add(lArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 60, -1));

        lCapacity.setBackground(new java.awt.Color(204, 255, 255));
        lCapacity.setText("Nama");
        background1.add(lCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        bSave.setText("Simpan");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        background1.add(bSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        bCancel.setText("Batal");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        background1.add(bCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));
        background1.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 230, -1));
        background1.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 230, -1));

        lUser1.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        lUser1.setText("Input Kategori Keuangan");
        background1.add(lUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 37, -1, -1));

        rtunaiy.setText("Ya");
        rtunaiy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtunaiyActionPerformed(evt);
            }
        });
        background1.add(rtunaiy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        rtunait.setText("Tidak");
        background1.add(rtunait, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        lNote2.setBackground(new java.awt.Color(204, 255, 255));
        lNote2.setText("Tunai");
        background1.add(lNote2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 60, -1));

        jckategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Harta", "Kewajiban", "Modal", "Pendapatan", "Beban" }));
        background1.add(jckategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 230, -1));
        background1.add(tsubid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 230, -1));

        lCapacity1.setBackground(new java.awt.Color(204, 255, 255));
        lCapacity1.setText("Kode");
        background1.add(lCapacity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));
        background1.add(tkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 230, -1));

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        background1.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
    try {
            Coa data = new Coa();
            data.setId(Integer.parseInt(tid.getText()));
            data.setParentId(Integer.parseInt(tsubid.getText()));
            data.setName(tnama.getText());
            data.setCode(Integer.parseInt(tkode.getText()));
            data.setCategoryId(jckategori.getSelectedIndex() + 1); // 1: Harta, 2: Kewajiban, dst
            data.setIsCash(rtunaiy.isSelected());

            CoaService service = new CoaService();
            if (coaSelected == null) {
                service.createCoa(data);
            } else {
                // Tambahkan method update jika diperlukan
                // service.update(data);
            }

            coaList.loadData();
            dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }


    }//GEN-LAST:event_bSaveActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        tid.setText("");
        tsubid.setText("");
        tnama.setText("");
        tkode.setText("");
        jckategori.setSelectedIndex(0);
        rtunaiy.setSelected(false);
        rtunait.setSelected(false);
    }//GEN-LAST:event_bHapusActionPerformed

    private void rtunaiyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtunaiyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtunaiyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartOfAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartOfAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartOfAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartOfAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChartOfAccountForm(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSave;
    private unindra.core.Background background1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jckategori;
    private javax.swing.JLabel lArea;
    private javax.swing.JLabel lCapacity;
    private javax.swing.JLabel lCapacity1;
    private javax.swing.JLabel lCode;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lNote2;
    private javax.swing.JLabel lUser1;
    private javax.swing.JRadioButton rtunait;
    private javax.swing.JRadioButton rtunaiy;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tkode;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tsubid;
    // End of variables declaration//GEN-END:variables
}
