package unindra.modules.datastore.coa.ui;

import javax.swing.JOptionPane;
import unindra.modules.datastore.coa.service.CoaService;
import unindra.modules.datastore.coa.model.Coa;

public class CoaForm extends javax.swing.JFrame {

    private CoaList list;

    private Coa selectedData;
    
    private int categoryId = 0;

    private int parentId;

    public CoaForm(CoaList list, Coa data) {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        this.list = list;
        fIsCash.setVisible(false);
        if (data != null) {
            title.setText("Edit Data Kategori Keuangan");
            selectedData = data;
            fCode.setText(String.valueOf(data.getCode()));
            fName.setText(data.getName());
            fNote.setText(data.getNote());
            fParent.setText(data.getParentName());
            fClass.setSelectedIndex(data.getCategoryId());
            if (data.getCategoryId()==1) {
                fIsCash.setVisible(true);
                fIsCash.setSelected(data.getIsCash());
            } else {
                fIsCash.setSelected(false);
            }
        }
    }

    private void setCategoryId() {
        categoryId = fClass.getSelectedIndex();
        if (categoryId == 1) {
            fIsCash.setVisible(true);
        } else {
            fIsCash.setVisible(false);
        }
    }

    private void lookupParent() {
        CoaList.openLookup(coa -> {
            if (coa != null) {
                parentId = coa.getId();
                fParent.setText(coa.getName());
                fCode.setText(String.valueOf(CoaService.nextCodeByParentId(parentId)));
                fName.requestFocus(true);
            }
        }, "parent", categoryId);
    }

    private void save() {
        Coa data = new Coa();
        try {
            int code = Integer.parseInt(fCode.getText());
            data.setCode(code);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Kode harus berupa angka.");
        }
        data.setName(fName.getText());
        data.setNote(fNote.getText());
        data.setParentId(parentId);
        data.setCategoryId(fClass.getSelectedIndex());
        data.setIsCash(fIsCash.isSelected());

        if (selectedData == null) {
            CoaService.create(data);
        } else {
            data.setId(selectedData.getId());
            CoaService.update(data);
        }
        list.loadData();
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new unindra.core.Background();
        lCode = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lParent = new javax.swing.JLabel();
        bSave = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        fCode = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        fParent = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        lClass = new javax.swing.JLabel();
        fClass = new javax.swing.JComboBox<>();
        fIsCash = new javax.swing.JCheckBox();
        lNote = new javax.swing.JLabel();
        fNote = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lCode.setBackground(new java.awt.Color(204, 255, 255));
        lCode.setText("Kode");

        lName.setBackground(new java.awt.Color(204, 255, 255));
        lName.setText("Nama");

        lParent.setBackground(new java.awt.Color(204, 255, 255));
        lParent.setText("Subklasifikasi");

        bSave.setText("Simpan");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bCancel.setText("Batal");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        fParent.setEditable(false);
        fParent.setText("Pilih Subklasifikasi...");
        fParent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fParentMouseClicked(evt);
            }
        });
        fParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fParentActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        title.setText("Tambah Data Kategori Keuangan");

        lClass.setBackground(new java.awt.Color(204, 255, 255));
        lClass.setText("Klasifikasi");

        fClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Klasifikasi...", "Harta", "Utang", "Kekayaan Bersih", "Penerimaan", "Pengeluaran" }));
        fClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fClassActionPerformed(evt);
            }
        });

        fIsCash.setText("Uang Tunai / Bank");

        lNote.setBackground(new java.awt.Color(204, 255, 255));
        lNote.setText("Catatan");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(bCancel)
                        .addGap(18, 18, 18)
                        .addComponent(bSave))
                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(lParent, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fParent, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(lCode, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fCode, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(lClass, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(title)
                                    .addComponent(fClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(background1Layout.createSequentialGroup()
                            .addComponent(lNote, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fIsCash)
                                .addComponent(fNote, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(title)
                .addGap(42, 42, 42)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lClass)
                    .addComponent(fClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lParent)
                    .addComponent(fParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCode)
                    .addComponent(fCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNote)
                    .addComponent(fNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fIsCash)
                .addGap(55, 55, 55)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bCancel))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        save();
    }//GEN-LAST:event_bSaveActionPerformed

    private void fParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fParentActionPerformed
        lookupParent();
    }//GEN-LAST:event_fParentActionPerformed

    private void fParentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fParentMouseClicked
        lookupParent();
    }//GEN-LAST:event_fParentMouseClicked

    private void fClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fClassActionPerformed
        setCategoryId();
    }//GEN-LAST:event_fClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoaForm(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bSave;
    private unindra.core.Background background1;
    private javax.swing.JComboBox<String> fClass;
    private javax.swing.JTextField fCode;
    private javax.swing.JCheckBox fIsCash;
    private javax.swing.JTextField fName;
    private javax.swing.JTextField fNote;
    private javax.swing.JTextField fParent;
    private javax.swing.JLabel lClass;
    private javax.swing.JLabel lCode;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lNote;
    private javax.swing.JLabel lParent;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
