package unindra.modules.auth.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Dimension;
import java.util.Calendar;
import java.util.Date;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.chart.ui.TextAnchor;
import org.jfree.data.category.DefaultCategoryDataset;

import unindra.modules.datastore.coa.ui.ChartOfAccountList;
import unindra.modules.datastore.contact.ui.ContactList;
import unindra.modules.datastore.project.ui.ProjectList;
import unindra.modules.datastore.budget.ui.BudgetList;
import unindra.modules.transaction.bill.ui.BillList;
import unindra.modules.transaction.cashin.ui.CashInList;
import unindra.modules.transaction.cashout.ui.CashOutList;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public MainMenu() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.DAY_OF_MONTH, 1);
        dateFrom.setDate(cal.getTime());
        dateTo.setDate(new Date());
        showDashboardChart();
    }

    private void showDashboardChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        double incomeBudget = 9300000;
        double expenseBudget = 7200000;
        double marginBudget = incomeBudget - expenseBudget;

        double incomeReal = 10000000;
        double expenseReal = 7000000;
        double marginReal = incomeReal - expenseReal;

        dataset.addValue(incomeBudget, "Anggaran", "Penerimaan");
        dataset.addValue(expenseBudget, "Anggaran", "Pengeluaran");
        dataset.addValue(marginBudget, "Anggaran", "Selisih");

        dataset.addValue(incomeReal, "Realisasi", "Penerimaan");
        dataset.addValue(expenseReal, "Realisasi", "Pengeluaran");
        dataset.addValue(marginReal, "Realisasi", "Selisih");

        JFreeChart chart = ChartFactory.createBarChart("Aktivitas Keuangan", "", "Nilai (Rp)", dataset);
        chart.setBackgroundPaint(null);
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(new Color(0, 0, 0, 0));
        plot.setOutlineVisible(false);
        plot.setRangeGridlinePaint(Color.GRAY);

        BarRenderer renderer = new BarRenderer();
        renderer.setSeriesPaint(0, new Color(60, 179, 113));
        renderer.setSeriesPaint(1, new Color(67, 140, 255));
        renderer.setDefaultItemLabelsVisible(true);
        renderer.setDefaultItemLabelGenerator(new StandardCategoryItemLabelGenerator());
        renderer.setDefaultItemLabelFont(new Font("SansSerif", Font.BOLD, 12));
        renderer.setDefaultPositiveItemLabelPosition(
            new ItemLabelPosition(ItemLabelAnchor.OUTSIDE12, TextAnchor.BASELINE_CENTER)
        );
        renderer.setBarPainter(new StandardBarPainter());
        renderer.setShadowVisible(false);
        renderer.setMaximumBarWidth(0.15);
        plot.setRenderer(renderer);
        ChartPanel panel = new ChartPanel(chart);
        panel.setPreferredSize(new Dimension(600, 400));
        panel.setOpaque(false);
        panel.setBackground(new Color(0, 0, 0, 0));
        Dashboard.setLayout(new BorderLayout());
        Dashboard.add(panel, BorderLayout.CENTER);
        Dashboard.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuTabbedPane = new javax.swing.JTabbedPane();
        Dashboard = new unindra.core.Background();
        dateFrom = new com.toedter.calendar.JDateChooser();
        dateTo = new com.toedter.calendar.JDateChooser();
        DataStore = new unindra.core.Background();
        bCOA = new javax.swing.JButton();
        bProject = new javax.swing.JButton();
        bContact = new javax.swing.JButton();
        bBudget = new javax.swing.JButton();
        Transaction = new unindra.core.Background();
        bCashIn = new javax.swing.JButton();
        bBill = new javax.swing.JButton();
        bCashOut = new javax.swing.JButton();
        Report = new unindra.core.Background();
        bProject6 = new javax.swing.JButton();
        bProject7 = new javax.swing.JButton();
        bProject8 = new javax.swing.JButton();
        bProject10 = new javax.swing.JButton();
        bProject11 = new javax.swing.JButton();
        bProject12 = new javax.swing.JButton();
        bProject13 = new javax.swing.JButton();
        bProject14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainMenuTabbedPane.setBackground(new java.awt.Color(222, 242, 251));
        MainMenuTabbedPane.setName(""); // NOI18N

        dateFrom.setDateFormatString("d-MMM-yyyy");

        dateTo.setDateFormatString("d-MMM-yyyy");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                .addContainerGap(760, Short.MAX_VALUE)
                .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(558, Short.MAX_VALUE))
        );

        MainMenuTabbedPane.addTab("Dasbor", new javax.swing.ImageIcon(getClass().getResource("/images/icon-analytics.png")), Dashboard); // NOI18N

        bCOA.setBackground(new java.awt.Color(32, 191, 107));
        bCOA.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bCOA.setForeground(new java.awt.Color(255, 255, 255));
        bCOA.setText("<html><body style=\"text-align:center\">Kategori<br />Keuangan</body></html>");
        bCOA.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bCOA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCOA.setDefaultCapable(false);
        bCOA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCOAActionPerformed(evt);
            }
        });

        bProject.setBackground(new java.awt.Color(211, 68, 233));
        bProject.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bProject.setForeground(new java.awt.Color(255, 255, 255));
        bProject.setText("<html><body style=\"text-align:center\">Data Proyek</body></html>");
        bProject.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProject.setDefaultCapable(false);
        bProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProjectActionPerformed(evt);
            }
        });

        bContact.setBackground(new java.awt.Color(40, 170, 233));
        bContact.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bContact.setForeground(new java.awt.Color(255, 255, 255));
        bContact.setText("<html><body style=\"text-align:center\">Data Kontak</body></html>");
        bContact.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bContact.setDefaultCapable(false);
        bContact.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bContactActionPerformed(evt);
            }
        });

        bBudget.setBackground(new java.awt.Color(245, 170, 59));
        bBudget.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bBudget.setForeground(new java.awt.Color(255, 255, 255));
        bBudget.setText("<html><body style=\"text-align:center\">Perencanaan<br />Anggaran</body></html>");
        bBudget.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bBudget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBudget.setDefaultCapable(false);
        bBudget.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBudgetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataStoreLayout = new javax.swing.GroupLayout(DataStore);
        DataStore.setLayout(DataStoreLayout);
        DataStoreLayout.setHorizontalGroup(
            DataStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataStoreLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(bCOA, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bContact, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bProject, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        DataStoreLayout.setVerticalGroup(
            DataStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataStoreLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(DataStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bProject, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bContact, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCOA, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        MainMenuTabbedPane.addTab("Data-data", new javax.swing.ImageIcon(getClass().getResource("/images/icon-box.png")), DataStore); // NOI18N

        bCashIn.setBackground(new java.awt.Color(74, 175, 77));
        bCashIn.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bCashIn.setForeground(new java.awt.Color(255, 255, 255));
        bCashIn.setText("<html><body style=\"text-align:center\">Transaksi<br />Penerimaan</body></html>");
        bCashIn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bCashIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCashIn.setDefaultCapable(false);
        bCashIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCashIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCashInActionPerformed(evt);
            }
        });

        bBill.setBackground(new java.awt.Color(255, 133, 133));
        bBill.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bBill.setForeground(new java.awt.Color(255, 255, 255));
        bBill.setText("<html><body style=\"text-align:center\">Tagihan</body></html>");
        bBill.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBill.setDefaultCapable(false);
        bBill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBillActionPerformed(evt);
            }
        });

        bCashOut.setBackground(new java.awt.Color(83, 170, 224));
        bCashOut.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bCashOut.setForeground(new java.awt.Color(255, 255, 255));
        bCashOut.setText("<html><body style=\"text-align:center\">Transaksi<br />Pengeluaran</body></html>");
        bCashOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bCashOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCashOut.setDefaultCapable(false);
        bCashOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCashOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCashOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransactionLayout = new javax.swing.GroupLayout(Transaction);
        Transaction.setLayout(TransactionLayout);
        TransactionLayout.setHorizontalGroup(
            TransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(bBill, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCashIn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCashOut, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        TransactionLayout.setVerticalGroup(
            TransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(TransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bBill, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bCashIn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bCashOut, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        MainMenuTabbedPane.addTab("Transaksi", new javax.swing.ImageIcon(getClass().getResource("/images/icon-payment.png")), Transaction); // NOI18N

        bProject6.setBackground(new java.awt.Color(211, 68, 233));
        bProject6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bProject6.setForeground(new java.awt.Color(255, 255, 255));
        bProject6.setText("<html><body style=\"text-align:center\">Laporan<br />Posisi Keuangan</body></html>");
        bProject6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bProject6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProject6.setDefaultCapable(false);
        bProject6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProject6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProject6ActionPerformed(evt);
            }
        });

        bProject7.setBackground(new java.awt.Color(40, 170, 233));
        bProject7.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bProject7.setForeground(new java.awt.Color(255, 255, 255));
        bProject7.setText("<html><body style=\"text-align:center\">Laporan<br />Arus Kas</body></html>");
        bProject7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bProject7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProject7.setDefaultCapable(false);
        bProject7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProject7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProject7ActionPerformed(evt);
            }
        });

        bProject8.setBackground(new java.awt.Color(32, 191, 107));
        bProject8.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bProject8.setForeground(new java.awt.Color(255, 255, 255));
        bProject8.setText("<html><body style=\"text-align:center\">Laporan<br />Aktivitas</body></html>");
        bProject8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bProject8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProject8.setDefaultCapable(false);
        bProject8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProject8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProject8ActionPerformed(evt);
            }
        });

        bProject10.setBackground(new java.awt.Color(255, 133, 133));
        bProject10.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bProject10.setForeground(new java.awt.Color(255, 255, 255));
        bProject10.setText("<html><body style=\"text-align:center\">Laporan<br />Tagihan</body></html>");
        bProject10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bProject10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProject10.setDefaultCapable(false);
        bProject10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProject10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProject10ActionPerformed(evt);
            }
        });

        bProject11.setBackground(new java.awt.Color(74, 175, 77));
        bProject11.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bProject11.setForeground(new java.awt.Color(255, 255, 255));
        bProject11.setText("<html><body style=\"text-align:center\">Laporan<br />Penerimaan</body></html>");
        bProject11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bProject11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProject11.setDefaultCapable(false);
        bProject11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProject11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProject11ActionPerformed(evt);
            }
        });

        bProject12.setBackground(new java.awt.Color(83, 170, 224));
        bProject12.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bProject12.setForeground(new java.awt.Color(255, 255, 255));
        bProject12.setText("<html><body style=\"text-align:center\">Laporan<br />Pengeluaran</body></html>");
        bProject12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bProject12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProject12.setDefaultCapable(false);
        bProject12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProject12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProject12ActionPerformed(evt);
            }
        });

        bProject13.setBackground(new java.awt.Color(245, 170, 59));
        bProject13.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bProject13.setForeground(new java.awt.Color(255, 255, 255));
        bProject13.setText("<html><body style=\"text-align:center\">Laporan<br />Realisasi<br />Anggaran</body></html>");
        bProject13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bProject13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProject13.setDefaultCapable(false);
        bProject13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProject13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProject13ActionPerformed(evt);
            }
        });

        bProject14.setBackground(new java.awt.Color(162, 120, 66));
        bProject14.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        bProject14.setForeground(new java.awt.Color(255, 255, 255));
        bProject14.setText("<html><body style=\"text-align:center\">Laporan<br />Proyek</body></html>");
        bProject14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bProject14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProject14.setDefaultCapable(false);
        bProject14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProject14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProject14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportLayout = new javax.swing.GroupLayout(Report);
        Report.setLayout(ReportLayout);
        ReportLayout.setHorizontalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportLayout.createSequentialGroup()
                        .addComponent(bProject10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bProject11, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bProject12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bProject14, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReportLayout.createSequentialGroup()
                        .addComponent(bProject8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bProject7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bProject6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bProject13, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        ReportLayout.setVerticalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bProject6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProject7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProject8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProject13, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bProject12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProject11, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProject10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProject14, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        MainMenuTabbedPane.addTab("Laporan", new javax.swing.ImageIcon(getClass().getResource("/images/icon-report.png")), Report); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCOAActionPerformed
        new ChartOfAccountList().setVisible(true);
    }//GEN-LAST:event_bCOAActionPerformed

    private void bProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProjectActionPerformed
        new ProjectList().setVisible(true);
    }//GEN-LAST:event_bProjectActionPerformed

    private void bContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bContactActionPerformed
        new ContactList().setVisible(true);
    }//GEN-LAST:event_bContactActionPerformed

    private void bCashInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCashInActionPerformed
        new CashInList().setVisible(true);
    }//GEN-LAST:event_bCashInActionPerformed

    private void bBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBillActionPerformed
        new BillList().setVisible(true);
    }//GEN-LAST:event_bBillActionPerformed

    private void bBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBudgetActionPerformed
        new BudgetList().setVisible(true);
    }//GEN-LAST:event_bBudgetActionPerformed

    private void bProject6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProject6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bProject6ActionPerformed

    private void bProject7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProject7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bProject7ActionPerformed

    private void bProject8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProject8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bProject8ActionPerformed

    private void bCashOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCashOutActionPerformed
        new CashOutList().setVisible(true);
    }//GEN-LAST:event_bCashOutActionPerformed

    private void bProject10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProject10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bProject10ActionPerformed

    private void bProject11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProject11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bProject11ActionPerformed

    private void bProject12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProject12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bProject12ActionPerformed

    private void bProject13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProject13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bProject13ActionPerformed

    private void bProject14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProject14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bProject14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private unindra.core.Background Dashboard;
    private unindra.core.Background DataStore;
    private javax.swing.JTabbedPane MainMenuTabbedPane;
    private unindra.core.Background Report;
    private unindra.core.Background Transaction;
    private javax.swing.JButton bBill;
    private javax.swing.JButton bBudget;
    private javax.swing.JButton bCOA;
    private javax.swing.JButton bCashIn;
    private javax.swing.JButton bCashOut;
    private javax.swing.JButton bContact;
    private javax.swing.JButton bProject;
    private javax.swing.JButton bProject10;
    private javax.swing.JButton bProject11;
    private javax.swing.JButton bProject12;
    private javax.swing.JButton bProject13;
    private javax.swing.JButton bProject14;
    private javax.swing.JButton bProject6;
    private javax.swing.JButton bProject7;
    private javax.swing.JButton bProject8;
    private com.toedter.calendar.JDateChooser dateFrom;
    private com.toedter.calendar.JDateChooser dateTo;
    // End of variables declaration//GEN-END:variables
}
