package unindra.modules.transaction.cashout.ui;

import java.util.Date;
import java.math.BigDecimal;
import java.time.ZoneId;
import javax.swing.JOptionPane;

import unindra.modules.transaction.core.service.TransactionService;
import unindra.modules.transaction.core.model.Transaction;
import unindra.modules.datastore.coa.ui.CoaList;

public class CashOutForm extends javax.swing.JFrame {

    private CashOutList list;

    private Transaction selectedData;
    
    private Integer coaId;

    public CashOutForm(CashOutList list, Transaction data) {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        this.list = list;
        if (data != null) {
            title.setText("Edit Transaksi Pengeluaran");
            selectedData = data;
            coaId = data.getTargetCoaId();
            fDate.setDate(Date.from(data.getTrxDate().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            fAmount.setText(data.getAmount().toPlainString());
        } else {
            Date now = new Date();
            fDate.setDate(now);
            fNumber.setText(String.valueOf(now.getTime() / 1000));
        }
    }

    private void lookupContact() {
        CoaList.openLookup(coa -> {
            if (coa != null) {
                coaId = coa.getId();
                fDate.requestFocus(true);
            }
        }, "child", 0);
    }

    private void lookupBill() {
        CoaList.openLookup(coa -> {
            if (coa != null) {
                coaId = coa.getId();
                fDate.requestFocus(true);
            }
        }, "child", 0);
    }
    
    private void lookupOriginCoa() {
        CoaList.openLookup(coa -> {
            if (coa != null) {
                coaId = coa.getId();
                fDate.requestFocus(true);
            }
        }, "child", 0);
    }

    private void lookupTargetCoa() {
        CoaList.openLookup(coa -> {
            if (coa != null) {
                coaId = coa.getId();
                fDate.requestFocus(true);
            }
        }, "child", 0);
    }

    private void lookupProject() {
        CoaList.openLookup(coa -> {
            if (coa != null) {
                coaId = coa.getId();
                fDate.requestFocus(true);
            }
        }, "child", 0);
    }
    
    private void save() {
        Transaction data = new Transaction();
        data.setTrxDate(fDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        try {
            BigDecimal amount = new BigDecimal(fAmount.getText());
            data.setAmount(amount);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Nilai anggaran harus berupa angka.");
        }

        if (selectedData == null) {
            TransactionService.create(data);
        } else {
            data.setId(selectedData.getId());
            TransactionService.update(data);
        }
        list.loadData();
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new unindra.core.Background();
        lCoaName = new javax.swing.JLabel();
        lDate = new javax.swing.JLabel();
        bSave = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        fDate = new com.toedter.calendar.JDateChooser();
        lAmount = new javax.swing.JLabel();
        fAmount = new javax.swing.JTextField();
        fNumber = new javax.swing.JTextField();
        lAmount1 = new javax.swing.JLabel();
        fContactName = new javax.swing.JTextField();
        lAmount2 = new javax.swing.JLabel();
        fBillNumber = new javax.swing.JTextField();
        lAmount3 = new javax.swing.JLabel();
        fOriginCoaName = new javax.swing.JTextField();
        lAmount4 = new javax.swing.JLabel();
        fTargetCoaName = new javax.swing.JTextField();
        lAmount5 = new javax.swing.JLabel();
        fProjectName = new javax.swing.JTextField();
        lAmount6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lCoaName.setBackground(new java.awt.Color(204, 255, 255));
        lCoaName.setText("No. Referensi");

        lDate.setBackground(new java.awt.Color(204, 255, 255));
        lDate.setText("Tanggal");

        bSave.setText("Simpan");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bCancel.setText("Batal");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        title.setText("Tambah Transaksi Pengeluaran");

        fDate.setDateFormatString("d-MMM-yyyy");

        lAmount.setBackground(new java.awt.Color(204, 255, 255));
        lAmount.setText("Nilai Pembayaran");

        fAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fAmount.setText("0");

        lAmount1.setBackground(new java.awt.Color(204, 255, 255));
        lAmount1.setText("Dibayar Kepada");

        fContactName.setEditable(false);
        fContactName.setText("Pilih Kontak...");
        fContactName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fContactNameMouseClicked(evt);
            }
        });
        fContactName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fContactNameActionPerformed(evt);
            }
        });

        lAmount2.setBackground(new java.awt.Color(204, 255, 255));
        lAmount2.setText("Tagihan");

        fBillNumber.setEditable(false);
        fBillNumber.setText("Pilih Tagihan...");
        fBillNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fBillNumberMouseClicked(evt);
            }
        });
        fBillNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fBillNumberActionPerformed(evt);
            }
        });

        lAmount3.setBackground(new java.awt.Color(204, 255, 255));
        lAmount3.setText("Dibayar Dengan");

        fOriginCoaName.setEditable(false);
        fOriginCoaName.setText("Pilih Kategori Keuangan...");
        fOriginCoaName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fOriginCoaNameMouseClicked(evt);
            }
        });
        fOriginCoaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fOriginCoaNameActionPerformed(evt);
            }
        });

        lAmount4.setBackground(new java.awt.Color(204, 255, 255));
        lAmount4.setText("Untuk Keperluan");

        fTargetCoaName.setEditable(false);
        fTargetCoaName.setText("Pilih Kategori Keuangan...");
        fTargetCoaName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fTargetCoaNameMouseClicked(evt);
            }
        });
        fTargetCoaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTargetCoaNameActionPerformed(evt);
            }
        });

        lAmount5.setBackground(new java.awt.Color(204, 255, 255));
        lAmount5.setText("Proyek");

        fProjectName.setEditable(false);
        fProjectName.setText("Pilih Proyek...");
        fProjectName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fProjectNameMouseClicked(evt);
            }
        });
        fProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fProjectNameActionPerformed(evt);
            }
        });

        lAmount6.setBackground(new java.awt.Color(204, 255, 255));
        lAmount6.setText("Catatan");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addContainerGap(807, Short.MAX_VALUE)
                        .addComponent(bCancel)
                        .addGap(18, 18, 18)
                        .addComponent(bSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, background1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(background1Layout.createSequentialGroup()
                                            .addComponent(lAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(fContactName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(background1Layout.createSequentialGroup()
                                            .addComponent(lDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(fDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addComponent(lAmount3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fOriginCoaName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addComponent(lAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(background1Layout.createSequentialGroup()
                                            .addComponent(lAmount4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(fTargetCoaName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(background1Layout.createSequentialGroup()
                                                .addComponent(lCoaName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(fNumber))
                                            .addGroup(background1Layout.createSequentialGroup()
                                                .addComponent(lAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(fBillNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                        .addComponent(lAmount5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(lAmount6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1)))))
                .addGap(31, 31, 31))
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title)
                .addGap(30, 30, 30)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDate)
                            .addComponent(fDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lAmount1)
                            .addComponent(fContactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCoaName))
                        .addGap(18, 18, 18)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lAmount2)
                            .addComponent(fBillNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lAmount3)
                            .addComponent(fOriginCoaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lAmount)))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lAmount4)
                            .addComponent(fTargetCoaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lAmount5)
                            .addComponent(fProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAmount6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bCancel))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        save();
    }//GEN-LAST:event_bSaveActionPerformed

    private void fContactNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fContactNameMouseClicked
        lookupContact();
    }//GEN-LAST:event_fContactNameMouseClicked

    private void fContactNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fContactNameActionPerformed
        lookupContact();
    }//GEN-LAST:event_fContactNameActionPerformed

    private void fBillNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fBillNumberMouseClicked
        lookupBill();
    }//GEN-LAST:event_fBillNumberMouseClicked

    private void fBillNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBillNumberActionPerformed
        lookupBill();
    }//GEN-LAST:event_fBillNumberActionPerformed

    private void fOriginCoaNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fOriginCoaNameMouseClicked
        lookupOriginCoa();
    }//GEN-LAST:event_fOriginCoaNameMouseClicked

    private void fOriginCoaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fOriginCoaNameActionPerformed
        lookupOriginCoa();
    }//GEN-LAST:event_fOriginCoaNameActionPerformed

    private void fTargetCoaNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fTargetCoaNameMouseClicked
        lookupTargetCoa();
    }//GEN-LAST:event_fTargetCoaNameMouseClicked

    private void fTargetCoaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTargetCoaNameActionPerformed
        lookupTargetCoa();
    }//GEN-LAST:event_fTargetCoaNameActionPerformed

    private void fProjectNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fProjectNameMouseClicked
        lookupProject();
    }//GEN-LAST:event_fProjectNameMouseClicked

    private void fProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fProjectNameActionPerformed
        lookupProject();
    }//GEN-LAST:event_fProjectNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashOutForm(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bSave;
    private unindra.core.Background background1;
    private javax.swing.JTextField fAmount;
    private javax.swing.JTextField fBillNumber;
    private javax.swing.JTextField fContactName;
    private com.toedter.calendar.JDateChooser fDate;
    private javax.swing.JTextField fNumber;
    private javax.swing.JTextField fOriginCoaName;
    private javax.swing.JTextField fProjectName;
    private javax.swing.JTextField fTargetCoaName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lAmount;
    private javax.swing.JLabel lAmount1;
    private javax.swing.JLabel lAmount2;
    private javax.swing.JLabel lAmount3;
    private javax.swing.JLabel lAmount4;
    private javax.swing.JLabel lAmount5;
    private javax.swing.JLabel lAmount6;
    private javax.swing.JLabel lCoaName;
    private javax.swing.JLabel lDate;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
