package unindra.modules.datastore.project.ui;

import java.math.BigDecimal;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import unindra.modules.datastore.project.service.ProjectService;
import unindra.modules.datastore.project.model.Project;
import unindra.modules.datastore.contact.ui.ContactList;

public class ProjectForm extends javax.swing.JFrame {

    private ProjectList list;

    private Project selectedData;
    
    private int customerId;

    public ProjectForm(ProjectList list, Project data) {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        this.list = list;
        if (data != null) {
            title.setText("Edit Data Proyek");
            selectedData = data;
            customerId = data.getId();
            fCustomerName.setText(data.getCustomerName());
            fNumber.setText(data.getNumber());
            fName.setText(data.getName());
            fDescription.setText(data.getDescription());
            fStartDate.setDate(Date.from(data.getStartDate().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            fDueDate.setDate(Date.from(data.getDueDate().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            fEndDate.setDate(Date.from(data.getEndDate().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            fAmount.setText(data.getAmount().toPlainString());
        } else {
            Date now = new Date();
            fNumber.setText(String.valueOf(now.getTime() / 1000));
            fStartDate.setDate(now);
            fDueDate.setDate(now);
            fEndDate.setDate(now);
        }
    }
    
    private void lookupCustomer() {
        ContactList.openLookup(data -> {
            if (data != null) {
                customerId = data.getId();
                fCustomerName.setText(data.getName());
                fName.requestFocus(true);
            }
        });
    }

    private void save() {
        Project data = new Project();
        data.setCustomerId(customerId);
        data.setNumber(fNumber.getText());
        data.setName(fName.getText());
        data.setDescription(fDescription.getText());
        data.setStartDate(fStartDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        data.setDueDate(fDueDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        data.setEndDate(fEndDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        try {
            BigDecimal amount = new BigDecimal(fAmount.getText());
            data.setAmount(amount);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Nilai anggaran harus berupa angka.");
        }
        
        if (selectedData == null) {
            ProjectService.create(data);
        } else {
            data.setId(selectedData.getId());
            ProjectService.update(data);
        }
        list.loadData();
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new unindra.core.Background();
        lCusomer = new javax.swing.JLabel();
        lNumber = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        bSave = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        fCustomerName = new javax.swing.JTextField();
        fNumber = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        lDescription = new javax.swing.JLabel();
        fDescription = new javax.swing.JTextField();
        fStartDate = new com.toedter.calendar.JDateChooser();
        lStartDate = new javax.swing.JLabel();
        lDueDate = new javax.swing.JLabel();
        lFinishDate = new javax.swing.JLabel();
        fDueDate = new com.toedter.calendar.JDateChooser();
        fEndDate = new com.toedter.calendar.JDateChooser();
        fAmount = new javax.swing.JTextField();
        lAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lCusomer.setBackground(new java.awt.Color(204, 255, 255));
        lCusomer.setText("Pelanggan");

        lNumber.setBackground(new java.awt.Color(204, 255, 255));
        lNumber.setText("Nomor Proyek");

        lName.setBackground(new java.awt.Color(204, 255, 255));
        lName.setText("Nama Proyek");

        bSave.setText("Simpan");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bCancel.setText("Batal");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        fCustomerName.setEditable(false);
        fCustomerName.setText("Pilih Pelanggan...");
        fCustomerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fCustomerNameMouseClicked(evt);
            }
        });
        fCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCustomerNameActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        title.setText("Tambah Data Proyek");

        lDescription.setBackground(new java.awt.Color(204, 255, 255));
        lDescription.setText("Deskripsi");

        fStartDate.setDateFormatString("d-MMM-yyyy");

        lStartDate.setBackground(new java.awt.Color(204, 255, 255));
        lStartDate.setText("Tanggal Mulai");

        lDueDate.setBackground(new java.awt.Color(204, 255, 255));
        lDueDate.setText("Target Selesai");

        lFinishDate.setBackground(new java.awt.Color(204, 255, 255));
        lFinishDate.setText("Tanggal Selesai");

        fDueDate.setDateFormatString("d-MMM-yyyy");

        fEndDate.setDateFormatString("d-MMM-yyyy");

        fAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fAmount.setText("0");

        lAmount.setBackground(new java.awt.Color(204, 255, 255));
        lAmount.setText("Nilai Proyek");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(background1Layout.createSequentialGroup()
                                    .addComponent(lNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(background1Layout.createSequentialGroup()
                                    .addComponent(lCusomer, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(background1Layout.createSequentialGroup()
                                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lFinishDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fName, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                                        .addComponent(fDueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                    .addComponent(lDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(bCancel)
                                .addGap(18, 18, 18)
                                .addComponent(bSave))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(lAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(301, 301, 301))))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCusomer)
                    .addComponent(fCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumber)
                    .addComponent(fNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDescription)
                    .addComponent(fDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lStartDate))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDueDate))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFinishDate))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAmount))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bCancel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        save();
    }//GEN-LAST:event_bSaveActionPerformed

    private void fCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCustomerNameActionPerformed
        lookupCustomer();
    }//GEN-LAST:event_fCustomerNameActionPerformed

    private void fCustomerNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fCustomerNameMouseClicked
        lookupCustomer();
    }//GEN-LAST:event_fCustomerNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectForm(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bSave;
    private unindra.core.Background background1;
    private javax.swing.JTextField fAmount;
    private javax.swing.JTextField fCustomerName;
    private javax.swing.JTextField fDescription;
    private com.toedter.calendar.JDateChooser fDueDate;
    private com.toedter.calendar.JDateChooser fEndDate;
    private javax.swing.JTextField fName;
    private javax.swing.JTextField fNumber;
    private com.toedter.calendar.JDateChooser fStartDate;
    private javax.swing.JLabel lAmount;
    private javax.swing.JLabel lCusomer;
    private javax.swing.JLabel lDescription;
    private javax.swing.JLabel lDueDate;
    private javax.swing.JLabel lFinishDate;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lNumber;
    private javax.swing.JLabel lStartDate;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
