package unindra.modules.report.ui;

import java.io.InputStream;
import java.sql.Connection;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
import unindra.core.Config;
import unindra.core.DB;
import unindra.modules.auth.ui.MainMenu;

public class ReportExpense extends javax.swing.JFrame {

    public ReportExpense() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.DAY_OF_MONTH, 1);
        fDateStart.setDate(cal.getTime());
        fDateEnd.setDate(new Date());
    }

    private void open() {
        try {
            InputStream file = MainMenu.class.getResourceAsStream("/reports/expense.jasper");
            HashMap<String, Object> params = new HashMap<>();
            params.put("date_start", Config.formatDate().format(fDateStart.getDate()));
            params.put("date_end", Config.formatDate().format(fDateEnd.getDate()));
            Connection connection = DB.getConnection();
            JasperPrint print = JasperFillManager.fillReport(file, params, connection);
            JFrame frame = new JFrame("Laporan Pengeluaran");
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.getContentPane().add(new JRViewer(print));
            frame.setSize(900, 700);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Laporan gagal dibuka : " + e.getMessage());
        } finally {
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new unindra.core.Background();
        bOpen = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        lUser = new javax.swing.JLabel();
        lUser1 = new javax.swing.JLabel();
        fDateStart = new com.toedter.calendar.JDateChooser();
        fDateEnd = new com.toedter.calendar.JDateChooser();
        bSetEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bOpen.setText("Buka");
        bOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpenActionPerformed(evt);
            }
        });

        bCancel.setText("Batal");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        lUser.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        lUser.setText("Tanggal");

        lUser1.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        lUser1.setText("Filter Laporan");

        fDateStart.setDateFormatString("d-MMM-yyyy");

        fDateEnd.setDateFormatString("d-MMM-yyyy");

        bSetEqual.setText(">");
        bSetEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
                background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(background1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(lUser1)
                                .addContainerGap(240, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                .addGroup(background1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(lUser)
                                                .addGap(18, 18, 18)
                                                .addComponent(fDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bSetEqual)
                                                .addGap(18, 18, 18)
                                                .addComponent(fDateEnd, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bCancel)
                                                .addGap(18, 18, 18)
                                                .addComponent(bOpen)))
                                .addGap(32, 32, 32)));
        background1Layout.setVerticalGroup(
                background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(background1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lUser1)
                                .addGap(41, 41, 41)
                                .addGroup(
                                        background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fDateStart, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bSetEqual)
                                                .addComponent(lUser))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190,
                                        Short.MAX_VALUE)
                                .addGroup(background1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bCancel)
                                        .addComponent(bOpen))
                                .addGap(25, 25, 25)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bCancelActionPerformed
        dispose();
    }// GEN-LAST:event_bCancelActionPerformed

    private void bOpenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bOpenActionPerformed
        open();
    }// GEN-LAST:event_bOpenActionPerformed

    private void bSetEqualActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bSetEqualActionPerformed
        fDateEnd.setDate(fDateStart.getDate());
    }// GEN-LAST:event_bSetEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportExpense.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportExpense.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportExpense.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportExpense.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportExpense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOpen;
    private javax.swing.JButton bSetEqual;
    private unindra.core.Background background1;
    private com.toedter.calendar.JDateChooser fDateEnd;
    private com.toedter.calendar.JDateChooser fDateStart;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel lUser1;
    // End of variables declaration//GEN-END:variables
}
